// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nywyyuraxpzweqgaadqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55d3l5dXJheHB6d2VxZ2FhZHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjE4MzIsImV4cCI6MjA1ODc5NzgzMn0.bllcjy6DIzFz_1BPEJfalCP_GflfJ_4a8stJV1zADNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);